export PATH="$HOME/.local/bin:$PATH"
source ~/dotfiles/zsh_modules/zsh_colors
source ~/dotfiles/zsh_modules/zsh_bash_scripts
source ~/dotfiles/zsh_modules/zsh_nvm
source ~/dotfiles/zsh_modules/zsh_default_editor
source ~/dotfiles/zsh_modules/zsh_yazi
source ~/dotfiles/zsh_modules/zsh_zoxide
source ~/dotfiles/zsh_modules/zsh_python
source ~/dotfiles/zsh_modules/zsh_node
source ~/dotfiles/zsh_modules/zsh_go
source ~/dotfiles/zsh_modules/zsh_xclip
source ~/dotfiles/zsh_modules/zsh_fzf
source ~/dotfiles/zsh_modules/zsh_ffmpeg
source ~/dotfiles/zsh_modules/zsh_mount
source ~/dotfiles/zsh_modules/zsh_mogrify
source ~/dotfiles/zsh_modules/zsh_dc_docker
source ~/dotfiles/zsh_modules/zsh_oh_my_zsh
source ~/dotfiles/zsh_modules/zsh_atuin
source ~/dotfiles/zsh_modules/zsh_aliases
source ~/dotfiles/zsh_modules/zsh_git
source ~/dotfiles/zsh_modules/zsh_find
