[module/filesystem-mnt]

; Mountpoints to display
mount-0 = /mnt

; Seconds to sleep between updates
; Default: 30
interval = 10

; Display fixed precision values
; Default: false
fixed-values = true

; Spacing (number of spaces, pixels, points) between entries
; Default: 2
spacing = 2

; Default: 90
; New in version 3.6.0
warn-percentage = 75

format-mounted = <label-mounted>
format-mounted-padding = 2

format-unmounted = <label-unmounted>

label-mounted =  %used% / %total%

label-unmounted = %mountpoint%: not mounted
label-unmounted-foreground = #55
